### ISSUE TITLE
Update dependencies of Reactive and ReactiveUI and Caliburn.Micro

### ISSUE THREAD

**Issue by jaredthirsk** [dchaib/Caliburn.Micro.ReactiveUI#28]
I am getting this exception at runtime:

Exception thrown: 'System.IO.FileLoadException' in Caliburn.Micro.ReactiveUI.dll
Additional information: Could not load file or assembly 'System.Reactive.Interfaces, Version=2.2.5.0

I need to use System.Reactive.Interfaces version 3.1.1.  I also have ReactiveUI.dll version 7.1.0 and Caliburn.Micro version 3.0.3.

I wonder how many other people are trying the nuget package and giving up, assuming this is obsolete?

**Comment by dchaib** [comment]
Thanks for letting me know! I'll investigate.

**Comment by dchaib** [comment]
ReactiveUI still has a dependency on RX 2. Since RX 3 packages are completely new versions of the same dlls with different public key tokens, this cannot be solved with binding redirects and the two cannot coexist in the same project. So we'll have to wait until ReactiveUI is compatible with RX 3. There is some work already underway reactiveui/ReactiveUI#1123.

Once it's done, I'll see if there are things to do on my side, but I don't think there will be.

**Comment by dchaib** [comment]
I finally took the time to check ReactiveUI 8 that brings compatibility with Reactive Extensions 3. As expected, it works without code changes.

Unfortunately, I took a dependency on `reactiveui-core` which no longer exists with v8. To fix this, I have published a new version (v2.4.0) that changes the dependency to `reactiveui`.

It is now available on [nuget](https://www.nuget.org/packages/Caliburn.Micro.ReactiveUI/2.4.0).

Feel free to try it out and let me know if you have issues!
